### ISSUE TITLE
OverflowError: Python integer <number>out of bounds for uint16

### ISSUE THREAD

**Issue by jinghan1997** [vnegnev/marcos_client#17]
Hi marcos developers, 

I am a user who has successfully installed and set up marcos before. I use Arch linux running on WSL on a window system. Recently, I re-setup everything on a new laptop but I am getting the following error when I run test_marga_model.py
OverflowError: Python integer <number>out of bounds for uint16

Every single test case fails and all give the same error where the triggering code lies in marcompile.py (lines 295, 231, 495).

I have set up marcos before in the same exact environment as mentioned above and it worked fine, but this current version doesn't pass the unit tests. I suspect its a new update of some sort(python libraries or marcos) that's causing the issue. Could you please check it out that if anyone else is facing the same error as well?

Thank you!

![image](https://github.com/user-attachments/assets/51758db8-b704-4058-a033-dc7cb7fbd3d2)
![image](https://github.com/user-attachments/assets/58df8816-cb94-4a1c-a31d-4f67ce1a55f6)
![image](https://github.com/user-attachments/assets/682b3efa-fadf-4c85-9892-e7b0a67b4949)

**Comment by vnegnev** [comment]
Hi, this is because Numpy 2.0 treats fixed-width integers and conversions differently from Numpy 1.x - I'm working on fixing the new bugs, hopefully in a day or two. In the meantime you can downgrade Numpy to 1.x to continue using the library as before.

**Comment by vnegnev** [comment]
Quick update - this should be fixed in https://github.com/vnegnev/marcos_client/pull/18 so please test it out and let me know if your problem is fixed.

**Comment by jinghan1997** [comment]
> Quick update - this should be fixed in #18 so please test it out and let me know if your problem is fixed.

Hi there, yup, I have checkout the pull request and the unit tests all pass now. 
Thanks for getting back and the quick fix!
